Renamed package and expanded `consolidate()` methods for resolving databases
globalgov/manydata pull request #193
Opened 2021-11-26 12:07 UTC by henriquesposito

# Description

These minor changes encompass changing the package name from `{qData}` to `{manydata}` as well as the expansion of methods for resolving databases for `consolidate()`.

## Package

* Closed #189 by renaming package from `{qData}` to `{manydata}`
* Updated user vignette to include more examples on working with `consolidate()`
* Improved package website

## Connection

* Improved `consolidate()` function
  * Closed #169 by making default key variable "qID_ref" instead of "qID"
  * Closed #183 by adding further methods to resolve conflicts between observations these methods now include:
    * Added "max" resolve argument which resolves conflicts in favor of the largest non NA value
    * Added "min" resolve argument which resolves conflicts in favor of the smallest non NA value
    * Added "mean" resolve argument which resolves conflicts in favor of the average non NA value
    * Added "median" resolve argument which resolves conflicts in favor of the median non NA value
    * Added "random" resolve argument which resolves conflicts in favor of a random non NA value
  * Closed #185 by making so that users can specify resolve argument differently for different variables
* Closed #188 by adding more informative warnings related to GitHub download limits for `get_packages()` function
* Added extraction functions to generate edgelists from agreements membership datasets
  * Added `extract_bilaterals()` for extracting adjacency edgelist for bilaterals agreements in a mixed edgelist
  * Added `extract_multilaterals()` for extracting adjacency edgelist for multilateral agreements in a mixed edgelist

# Checklist:

- [ ] PR form
  - [ ] I have given this pull request an informative title
  - [ ] Description above itemizes changes under subtitles, e.g. "## Collection""
  - [ ] Any closed, fixed, or related issues are referenced and explained in the description above, e.g. "Fixed #0 by adding A"
  - [ ] Package builds on my OS without issues
- [ ] PR checks all pass for latest commit
  - [ ] Package builds on Mac
  - [ ] Package builds on Windows
  - [ ] Package builds on Linux
  - [ ] CodeCov check: Package improves or maintains good test coverage
  - [ ] CodeFactor check: Package improves or maintains good style
- [ ] Documentation
  - [ ] Any new or modified functions or data have roxygen style documentation in their .R scripts
  - [ ] Any longer functions are commented inline so that it is easier to debug in the future
  - [ ] PR description above and the NEWS.md file are aligned
  - [ ] DESCRIPTION file version is bumped by the appropriate increment (major, minor, patch)

2021-12-01 15:42 UTC, BBieri reviewed
Great! Couldn't find anything major, apart from some minor grammatical things in the `pkgdown.yml` and the `README.rmd`.

2021-12-01 15:42 UTC, BBieri commented on DESCRIPTION
> +Date: 2021-01-12
Update the date

2021-12-01 15:42 UTC, BBieri commented on README.Rmd
> +`{manydata}` offers users access to all of the tested data in the various many packages available in the universe,
Both `{manytrade}` and `{manystates}` put the expression many packages in "code format" like this: `many packages`. This is to avoid weird sentence structures and make clear to the reader that we talk about "our many packages" and not just many packages. What do you think about this?

2021-12-01 15:42 UTC, BBieri commented on README.Rmd
> +The `get_packages()` function can be used to discover the many packages currently available.
Example of the comment above, many packages may refer to other packages if it is not written as `manypackages`. What do you think ?

2021-12-01 15:42 UTC, BBieri commented on pkgdown/_pkgdown.yml
> +    desc: "These functions are to assist data analysts with analysing data on particular parts of global governance"
"assist data analysts with the analysis of data" sounds better in this case I think

2021-12-01 15:42 UTC, BBieri commented on pkgdown/_pkgdown.yml
> +    desc: "These functions are to assist data analysts with wrangling data on particular parts of global governance"
Same, I would put a "the" between with and wrangling.

2021-12-02 07:01 UTC, jaeltan commented on NEWS.md
> +  * Added `extract_bilaterals()` for extracting adjacency edgelist for bilaterals agreements
'bilateral agreements' instead of bilateral**s** agreements

2021-12-02 07:03 UTC, jaeltan commented on NEWS.md
> +
Do we need to add that there is a change from qID to treaty_ID and qID_ref to many_ID?

2021-12-02 07:04 UTC, jaeltan commented on R/consolidate.R
> +#' This provides users with considerable flexibility in how they combine manydata.
lintr issue about line more than 80 characters here

2021-12-02 07:06 UTC, jaeltan commented on R/consolidate.R
> +#' @param resolve How conflicts between observations should be resolved?
Grammar issue - could change to 'Specify how conflict between observations should be resolved.' or 'How should conflicts between observations be resolved?'

2021-12-02 07:07 UTC, jaeltan commented on R/consolidate.R
> +#' "median" takes the meadian value.
Spelling error: should be 'median' not meadian

2021-12-02 07:09 UTC, jaeltan commented on R/package_get.R
> +#' Find and download packages in the many universe
Question: is it many packages universe or just many universe?

2021-12-02 07:09 UTC, jaeltan commented on R/package_get.R
> +#' Find and download packages in the many universe
same question here (and in line 6)

2021-12-02 07:10 UTC, jaeltan commented on R/package_get.R
> +#' the many universe of data packages. It allows for users to rapidly access
'for' is redundant I think

2021-12-02 07:11 UTC, jaeltan commented on R/package_get.R
> +#' universe, they can to type the package name within the function.
remove 'to'

2021-12-02 07:13 UTC, jaeltan commented on R/report_data.R
> +#' report data a specific database in a many package
add 'on' between 'data' and 'a specific database'?

2021-12-02 07:16 UTC, jaeltan commented on README.Rmd
> +`{manydata}` is the central package in the many universe of qPackages aimed at collecting, connecting and correcting network data across issue-domains of global governance. To assist users in doing s
should be 'many packages universe'? Also, as Bernie commented, I think formatting the `many packages` might be useful to make it clearer that we are referring to the name of our set of packages?

2021-12-02 07:17 UTC, jaeltan commented on README.Rmd
> +A special feature of the many universe of packages is that it is not 'opinionated' - instead of
`many packages` universe here as well?

2021-12-02 07:17 UTC, jaeltan commented on README.Rmd
> +the packages in the many universe gather well-regarded datasets in each issue-domain into three-dimensional 'datacubes'.
same here?

2021-12-02 07:18 UTC, jaeltan commented on README.Rmd
> +The `get_packages()` function can be used to discover the many packages currently available.
Agree with @BBieri

2021-12-02 07:23 UTC, jaeltan commented on tests/testthat/test_UNRV.R
> +# Test if  meets the many universe requirements
many packages universe?

2021-12-02 07:24 UTC, jaeltan commented on tests/testthat/test_britannica.R
> +# Test if  meets the many universe requirements
same  here

2021-12-02 07:24 UTC, jaeltan commented on tests/testthat/test_consolidate.R
> +data1 <- dplyr::tibble(many_ID = c("NZL", "BRA", "CHF"),
Should it be treaty_ID here instead of many_ID because it was qID before the change?

2021-12-02 07:27 UTC, jaeltan commented on tests/testthat/test_wikipedia.R
> +# Test if  meets the many universe requirements
same here

2021-12-02 07:27 UTC, jaeltan commented on vignettes/user.Rmd
> +Packages in the many universe have the advantage to facilitate comparison
same here

2021-12-02 07:29 UTC, jaeltan requested changes
Hi @henriquesposito , I think this was already very well done so I only had a few minor comments on syntax/grammar. Hope it helps!

2021-12-02 09:17 UTC, henriquesposito commented on README.Rmd
> +`{manydata}` offers users access to all of the tested data in the various many packages available in the universe,
Agreed, we can do this in the READMEs across!

2021-12-02 10:06 UTC, henriquesposito commented on NEWS.md
> +
Added on line 13

2021-12-02 10:28 UTC, henriquesposito commented on R/package_get.R
> +#' Find and download packages in the many universe
Here it is many packages universe because it refers to the qPackage ecosytem, I will change it.

2021-12-02 12:07 UTC, jaeltan approved these changes

2021-12-02 14:36 UTC, merged