Improved `consolidate()` function and updated package website
globalgov/manydata pull request #200
Opened 2022-03-02 13:58 UTC by henriquesposito

# Description

These patch changes improve `consolidate()` function by making it more concise and update the package website to work with the new `{pkgdown}` version release.

## Package

* Updated package website
  * Closed #196 by updating elements that configure website to work properly
  * Updated `{pkgdown}` to use bootstrap 5 template
* Closed #194 by updating all remaining references from qID to manyID

## Connection

* Updated `consolidate()` function
  * Closed #191 by making `consolidate()` function more concise
  * Fixed warnings by changing how ´{messydates}` package resolves dates
  * Updated how `consolidate()` substitutes NAs observations left with first non-missing observation
* Closed #199 by adding `favour()` function that re-orders datasets within a database

# Checklist:

- [ ] PR form
  - [ ] I have given this pull request an informative title
  - [ ] Description above itemizes changes under subtitles, e.g. "## Collection""
  - [ ] Any closed, fixed, or related issues are referenced and explained in the description above, e.g. "Fixed #0 by adding A"
  - [ ] Package builds on my OS without issues
- [ ] PR checks all pass for latest commit
  - [ ] Package builds on Mac
  - [ ] Package builds on Windows
  - [ ] Package builds on Linux
  - [ ] CodeCov check: Package improves or maintains good test coverage
  - [ ] CodeFactor check: Package improves or maintains good style
- [ ] Documentation
  - [ ] Any new or modified functions or data have roxygen style documentation in their .R scripts
  - [ ] Any longer functions are commented inline so that it is easier to debug in the future
  - [ ] PR description above and the NEWS.md file are aligned
  - [ ] DESCRIPTION file version is bumped by the appropriate increment (major, minor, patch)

2022-03-03 05:16 UTC, jhollway requested changes
Thanks @henriquesposito , I'm not finished going through it all, but here's a few comments to start with.

2022-03-03 05:16 UTC, jhollway commented on NEWS.md
> +# manydata 0.6.1
If this is the CRAN release, better start with a new (minor) version

2022-03-03 05:16 UTC, jhollway commented on DESCRIPTION
>  Date: 2021-12-03
Bump #minor. Also, Date needs updating...

2022-03-03 05:16 UTC, jhollway commented on DESCRIPTION
>  Title: An R Portal for Ensembled Global Governance Data
Maybe doesn't need 'R' in the package title? Can't remember the CRAN regulations on this...

2022-03-03 05:16 UTC, jhollway commented on NAMESPACE
> +export(favour)
Does this need to be also re-exported as `favor` for our American cousins?

2022-03-03 05:16 UTC, jhollway commented on NEWS.md
> +  * Fixed warnings by changing how ´{messydates}` package resolves dates
There's a front tick instead of a backtick on this line, and it confuses the syntax highlighter.

2022-03-03 05:16 UTC, jhollway commented on man/favour.Rd
> +
This comment is for the logo -- it seems that it has shrunk considerably... Does this have any effect on how it shows on the website?

2022-03-03 05:16 UTC, jhollway commented on man/coalesce_compatible.Rd
>  \examples{
This comment is for the logo -- it seems to have shrunk? Could this impact how it displays on the website/README?

2022-03-03 11:39 UTC, henriquesposito commented on man/favour.Rd
> +
I see what you mean... I have changed the logo size specifications on the README file, but it seems now that the image quality become worse. @BBieri could you please take a look at the logo size and quality in the package README and website for manydata if you have a few minutes? Thank you.

2022-03-05 04:45 UTC, jhollway requested changes
A few more ideas, thanks @henriquesposito

2022-03-05 04:45 UTC, jhollway commented on DESCRIPTION
> +    R (>= 3.5.0)
Note that if we can avoid pointblank, we can go back to 3.4.0 -- if pointblank is only really used for manypkgs, maybe we can drop it?

2022-03-05 04:45 UTC, jhollway commented on DESCRIPTION
> +Title: An Portal for Ensembled Global Governance Data
A Portal

2022-03-05 04:45 UTC, jhollway commented on pkgdown/_pkgdown.yml
> +  - title: "Downloading many packages and inspecting data"
Phrasing could be confusing? Maybe 'many* packages' or 'manydata packages'?

2022-03-05 04:45 UTC, jhollway commented on pkgdown/_pkgdown.yml
> +    desc: "These functions are to assist data analysts with the download of data on particular domains of global governance"
Delete 'are to'

2022-03-05 04:45 UTC, jhollway commented on pkgdown/_pkgdown.yml
> +    desc: "These functions are to assist data analysts with the wrangling of data on particular domains of global governance"
Delete 'are to'

2022-03-05 04:45 UTC, jhollway commented on pkgdown/_pkgdown.yml
> +    desc: "These functions are to assist data analysts with the wrangling of data on particular domains of global governance"
Maybe add a little more explanation? Something like: "Ensembled data adds special challenges to data wrangling. These functions assist analysts with wrangling such data"

2022-03-05 04:45 UTC, jhollway commented on pkgdown/_pkgdown.yml
> +    desc: "These functions assist data analysts with the analysis of data on particular domains of global governance"
What's the difference between 'working with' and 'data wrangling'? Is there a more useful or informative way of categorising these functions?

2022-03-05 04:45 UTC, jhollway commented on pkgdown/_pkgdown.yml
> +    devs: Developed by [James Hollway](https://jameshollway.com/).
It's a team product. Just the panarchic link is fine here.

2022-03-05 04:45 UTC, jhollway commented on R/releases_plot.R
> -#' @import lubridate
Is this the only function in the package with some of these dependencies, e.g. `ggplot2`? If so, do we really need the function here/on GitHub? If not, we can trim the package a little?

2022-03-05 04:45 UTC, jhollway commented on R/package_get.R
>             https://github.com/globalgov")
Does this stop message print all on one line or on separate lines? Maybe we want to print on separate lines?

2022-03-05 04:45 UTC, jhollway commented on R/extract.R
> +#' Extracting adjacency edgelist for international agreements
Does this only work on edgelists? Is 'edgelist' a known term for all those who might use the package? Could some users want to `extract_bilaterals()` just on the 'novelist' (as it were)?

2022-03-05 04:45 UTC, jhollway commented on R/consolidate.R
> +#' (.i.e. last dataset should be favoured over previous).
This is not a clear parameter description. The question posed suggests that a logical (TRUE/FALSE) answer is expected, but the example suggests that it's the name of one or more datasets?

2022-03-05 04:45 UTC, jhollway commented on R/consolidate.R
>  r_min <- function(other_variables, out, key) {
I find these functions really useful. Though I like the use of a prefix to avoid conflicts etc, I wonder whether in the greater `R` ecosystem `r_*` could be misunderstood? Maybe `res_*`, `rsv_*`, or `resolve_*` could work?

2022-03-07 14:24 UTC, henriquesposito commented on R/releases_plot.R
> -#' @import lubridate
Yes, this is the case only for the `ggplot2` dependency ... Though I like having this function to complement the `get_packages()`function and help manydata to be the portal, I understand if you want to move it elsewhere. Just let me know.

2022-03-07 14:34 UTC, BBieri commented on man/favour.Rd
> +
I made this change following the update to a Bootstrap 5 based package website to be consistent with the `{tidyverse}` package logo sizes (see [the `{ggplot}` repository on GitHub](https://github.com/tidyverse/ggplot2/)). Let me know if you would like me to revert and keep the big logo @jhollway @henriquesposito.

2022-03-07 14:37 UTC, henriquesposito commented on R/package_get.R
>             https://github.com/globalgov")
It prints in separate lines

2022-03-09 04:28 UTC, jhollway requested changes

2022-03-09 04:28 UTC, jhollway commented on R/consolidate.R
> +#' Selects a single dataset from a database
Can we add a bit more explanation here, for example where it comes from?

2022-03-09 09:07 UTC, henriquesposito commented on R/consolidate.R
> +#' Selects a single dataset from a database
I added a bit more explanation in a details section. We cannot add a new description for functions that are reexported, we get a warning if we do so. Thank you.

2022-03-10 01:34 UTC, jhollway requested changes

2022-03-10 01:34 UTC, jhollway commented on R/releases_plot.R
> -#' @import lubridate
Let's keep it for now, but it seems a candidate for being dropped at some stage.

2022-03-10 01:34 UTC, jhollway commented on R/extract.R
> +#' @name extraction
Isn't it `@rdname`?

2022-03-10 01:34 UTC, jhollway commented on R/extract.R
> +#' in the many packages universe.
A little more explanation of use cases? For example, should it be used before or after consolidating?

2022-03-10 01:34 UTC, jhollway commented on R/extract.R
> +#' @importFrom dplyr filter
If you have `@import dplyr` above, you don't need `@importFrom dplyr ...` anywhere

2022-03-10 01:34 UTC, jhollway commented on R/data_report.R
> +#' Note that there is no original codebook for the GNEVAR database
Do we explain what GNEVAR is anywhere? Do we really want to advertise that our contribution doesn't have a codebook?

2022-03-10 01:34 UTC, jhollway commented on R/consolidate.R
> +favor <- favour
Is this the recommended way of managing function aliases?

2022-03-10 07:06 UTC, jaeltan commented on DESCRIPTION
> +Date: 2022-03-08
Update date?

2022-03-10 07:13 UTC, jaeltan commented on R/consolidate.R
>      out <- out %>% dplyr::select(all_of(key), starts_with(all_variables))
do we need to add the 'all_of', 'starts_with' functions to importFrom list above?

2022-03-10 07:37 UTC, jaeltan commented on R/consolidate.R
> +#' @return The selected database
does it return a dataset or a database?

2022-03-10 07:45 UTC, jaeltan commented on R/consolidate.R
> +#' atasets within the database to be favoured over others.
missing 'd' in 'datasets within the database'

2022-03-10 07:54 UTC, jaeltan commented on R/wrangling_data.R
> +#' transmutate(emperors$wikipedia, Beggining = Beg)
Beginning

2022-03-10 07:58 UTC, jaeltan commented on vignettes/user.Rmd
> +To make it easier to identify of all packages in the
remove 'of'

2022-03-10 07:59 UTC, jaeltan commented on vignettes/user.Rmd
> +The `consolidate()` function which facilitates consolidating a set of datasets, or a database,
remove 'which'

2022-03-10 08:03 UTC, jaeltan reviewed
Hi Henrique, I didn't have much to add except some minor spelling/wording issues. Thanks and good job!

2022-03-10 13:13 UTC, henriquesposito commented on R/consolidate.R
> +favor <- favour
If we want users to use the function and access the documentation, I think exporting is perhaps a more explicit way to do so. I previously tried to simply document as an alias and/or use the <- call (i.e. favour <- favor <- function ...), but had issues both approaches when trying to use and/access documentation for the function after loading the package locally. However, if you have any other ideas in how we should manage aliases please let me know and I will gladly change it. Thank you.

2022-03-14 10:57 UTC, BBieri approved these changes

2022-03-22 01:51 UTC, jhollway commented
@jaeltan, can you please go through once more and explicitly approve this PR then?
@BBieri, would you like to add your point about vector keys for `consolidate()` to this PR?

2022-03-22 20:21 UTC, jhollway requested changes
A few more ideas here and there...

2022-03-22 20:21 UTC, jhollway commented on NEWS.md
> +  * Updated `{pkgdown}` to use bootstrap 5 template
The package is not updated, it is the `_pkgdown.yaml` file that has been updated. Also, I'm still unclear what bootstrap 5 adds for us?

2022-03-22 20:21 UTC, jhollway commented on NEWS.md
> +* Closed #199 by adding `favour()` function that re-orders datasets within a database
Can we reword this to be a little more assertive/advertising? After all, this is the release that finally makes it on to CRAN... ;)

2022-03-22 20:21 UTC, jhollway commented on R/wrangling_data.R
> +#' transmutate(emperors$wikipedia, Beginning = Beg)
Can we add a line to show a before and after? e.g.

```
emperors$wikipedia
transmutate(emperors$wikipedia, Beginning = Beg)
```

2022-03-22 20:21 UTC, jhollway commented on R/extract.R
> +#' Extracting international agreements
I'm wondering whether "get" might be a more useful verb here than "extract", e.g. `get_bilaterals()`?

2022-03-22 20:21 UTC, jhollway commented on R/consolidate.R
> +#' resolve = c(Beg = "min", End = "max"), key = "ID")
Maybe for these examples it would be useful to add the argument names. It's more verbose, but perhaps users would appreciate the examples being explicit?

2022-03-23 09:04 UTC, henriquesposito commented on NEWS.md
> +  * Updated `{pkgdown}` to use bootstrap 5 template
Yes, that is correct, thank you. I have changed the NEWS description to reflect such. As I understand, for the bootstrap 5 template upgrade, it reduces the chances of the website braking down and makes the CSS for the website a bit more programmable/flexible. However, @BBieri might be better equipped to tell you more about this upgrade.

2022-03-23 09:59 UTC, henriquesposito commented on R/extract.R
> +#' Extracting international agreements
I agree, this is also a bit more consistent with some of the other functions in the package as get_packages().

2022-03-24 22:39 UTC, jhollway commented on R/consolidate.R
>      out <- out %>% dplyr::select(all_of(key), starts_with(all_variables))
Need to prefix `all_of` and `starts_with` with package names

2022-03-24 22:39 UTC, jhollway commented on R/consolidate.R
>      all_variables <- names(table(all_variables)[table(all_variables) == length(database)])
Long line?

2022-03-24 22:39 UTC, jhollway commented on R/consolidate.R
>                          resolve = c("coalesce", "min", "max", "median", "mean", "random"),
Long line?

2022-03-24 22:39 UTC, jhollway commented on R/consolidate.R
>  consolidate <- function(database,
Apparently this function has become overly complex (many if statements) -- can we reduce the number of switch points and/or unpack the function somehow?

2022-03-24 22:39 UTC, jhollway commented on R/consolidate.R
>      out <- out %>% dplyr::select(-dplyr::starts_with(var))
Are we re-exporting `%>%`? Otherwise we should try and avoid using this inside of functions

2022-03-24 22:39 UTC, jhollway commented on R/consolidate.R
> +    out <- dplyr::select(out, all_of(key), other_variables)
Need to prefix `all_of` with package name

2022-03-24 22:39 UTC, jhollway commented on R/consolidate.R
> +    out <- dplyr::select(out, all_of(key), other_variables)
Need to prefix `all_of` with package name

2022-03-24 22:39 UTC, jhollway commented on R/consolidate.R
> +    out <- dplyr::select(out, all_of(key), other_variables)
Need to prefix `all_of` with package name

2022-03-25 14:44 UTC, henriquesposito commented on R/consolidate.R
>  consolidate <- function(database,
I reduced the complexity from 27 to 16 by adding helper functions to resolve variables for unique or multiple arguments. I can reduce this complexity further, but I have the impression that we would have too many layers of helper functions (i.e. helper functions that call other helper functions). Would you like me to reduce it more? Thank you.

2022-03-28 08:40 UTC, jaeltan commented on R/consolidate.R
> +#' This function consolidates a set of datasets in a 'many* package' database
Should we add a note about the naming of variables? So that users don't run into the same problems that we did

2022-03-28 09:04 UTC, jaeltan reviewed
Thanks Henrique for all the hard work on manydata! I just made a few minor comments. Also I pushed the changes to the cheatsheet files to the /inst folder but the readme seems to use the one from the /man/figures folder, should I move the edited ones over to the /man/figures folder and remove the ones from /inst?

2022-03-28 09:04 UTC, jaeltan commented on R/consolidate.R
> +#' please add datasets increasing order of importance
minor rephrase: 'please list datasets in increasing order of importance'

2022-03-28 11:15 UTC, henriquesposito commented on R/consolidate.R
> +#' This function consolidates a set of datasets in a 'many* package' database
Thank you for the comment Jael, but I actually already fixed the issue with ambiguous variable names. I do think that maybe, in manypkgs, we could add a sentence on the preparation script about how having one letter variable names is not recommend. What do you think?

2022-03-28 11:19 UTC, jaeltan commented on R/consolidate.R
> +#' This function consolidates a set of datasets in a 'many* package' database
I think that's a good idea, thank you!

2022-03-28 11:27 UTC, jaeltan commented on R/treaties_get.R
> +#' Researchers can, for example, use `get_bilaterals()` to retrieve
I think it's fine, I just wanted to clarify that `get_bilaterals()` returns the countries but `get_multilaterals()` doesn't

2022-03-29 09:09 UTC, BBieri approved these changes

2022-03-29 09:54 UTC, henriquesposito commented on R/consolidate.R
>  consolidate <- function(database,
I reduced the complexity below 15 just in case. Thank you.

2022-03-30 04:36 UTC, jhollway approved these changes

2022-03-30 07:21 UTC, merged