Fixed bugs with `get_packages()` and added `db_heatmap()` function
globalgov/manydata pull request #260
Opened 2023-05-25 09:39 UTC by henriquesposito

# Description

This patch PR fixed bugs with `get_packages()` function, added `db_heatmap()` function, improved `plot-releases()` function and 'db_profile' family of functions.

## Package

* Closed #259 by revising CCC package structure and updating the package cheatsheet

## Connection

* Closed #243 and #257 by creating a `db_heatmap()` function to visually compare datasets in a 'many' database
* Closed #248 by updating `map_plot()` function and adding `agreements_plot()`, `lineages_plot()`, and `memberships_plot()` functions for easy plotting of 'many' data
* Closed #249 by updating variable categories in `db_plot()` function
* Closed #250 by fixing numeric selection within `get_packages()` function
* Closed #251 by adding 'update' argument to `get_packages()` function to allow users to update 'many' packages not up to date
* Closed #253 by separating `db_plots()` into an user facing and non-user facing functions for internal use only

# Checklist:

- [ ] PR form
  - [ ] I have given this pull request an informative title
  - [ ] Description above itemizes changes under subtitles, e.g. "## Collection""
  - [ ] Any closed, fixed, or related issues are referenced and explained in the description above, e.g. "Fixed #0 by adding A"
  - [ ] Package builds on my OS without issues
- [ ] PR checks all pass for latest commit
  - [ ] Package builds on Mac
  - [ ] Package builds on Windows
  - [ ] Package builds on Linux
  - [ ] CodeCov check: Package improves or maintains good test coverage
  - [ ] CodeFactor check: Package improves or maintains good style
- [ ] Documentation
  - [ ] Any new or modified functions or data have roxygen style documentation in their .R scripts
  - [ ] Any longer functions are commented inline so that it is easier to debug in the future
  - [ ] PR description above and the NEWS.md file are aligned
  - [ ] DESCRIPTION file version is bumped by the appropriate increment (major, minor, patch)

2023-06-16 17:50 UTC, henriquesposito commented
@jaeltan besides the vignette and reviewing/adding tests (issue #276) as well as updating manydata-defunct script (issue #277), I am taking note here of a few other things I would like you to please take a look at when going through the PR:

- Could you please take a look at the `call_sources()` outputs and tests? The function returns a 'tibble' but I am not sure the printing is ideal... either we have to make sure printing is better or we might want to default to base R printing (as we do in `messydates::mreport()`)... Also, tests appear not to work so they have been commented out. Notice that this function requires a completely new documentation style (see the 'emperors' documentation file in manydata). I have also commented in the respective issue.
- Could you please review the dependencies and see if we can move anything else to suggests (take a look at how we do this in the `plot_overlap()`for example)?
- Could you please take a look at why the PR checks appear not to be running?
- Could you please take a look at the merge conflicts (this is caused because we merged a feature branch today to fix a CRAN related issue with the package dependencies)?

Thank you so much in advance for all your help!

2023-06-23 10:48 UTC, jaeltan reviewed
Thanks @henriquesposito for all the hard work on manydata! I've added the functions to manydata-defunct.R, added a few tests, and updated the vignette and README, hope this helps. Please also let me know when you've finalised everything then I can update the cheatsheet.

2023-06-23 10:48 UTC, jaeltan commented on R/agreements_plot.R
> +#' Other options are "bilateral" or "multilateral".
This didn't seem to work when I tried it

2023-06-23 10:48 UTC, jaeltan commented on R/agreements_plot.R
> +#' or a "consolidated" database.
I removed the line 'Other options are "bilateral" or "multilateral".' since it didn't seem to fit in here

2023-06-23 10:48 UTC, jaeltan commented on vignettes/user.Rmd
>  we expect that their developers will instead choose
I'm not sure what this sentence is supposed to convey to users about the many packages?

2023-06-23 10:48 UTC, jaeltan commented on R/call.R
> +  helptext <- utils::help(topic = as.character(database),
Just a note, I've uncommented the test for call_sources() because it now passes, but there were a few times where it didn't when I was running it on my end and the failure was because utils::help() couldn't pick up the path for the 'emperors' help file.

2023-06-26 12:29 UTC, henriquesposito commented on R/call.R
> +  helptext <- utils::help(topic = as.character(database),
Thank you @jaeltan !

2023-06-27 12:00 UTC, jaeltan approved these changes
Some very minor comments, thanks @henriquesposito !

2023-06-27 14:04 UTC, jhollway submitted a review, later dismissed

2023-06-27 14:04 UTC, jhollway commented on R/compare.R
> +#' allows users to visualize the comparisons.
There is an awful lot of different functions on this page too. Again, perhaps more separate documentation, and we can always connect the pages where helpful by using `@family`.

2023-06-27 14:04 UTC, jhollway commented on vignettes/user.Rmd
> +signature, entry into force, and end dates of treaties respectively.
Maybe keep Begin and End separate from Signature, Force, and End to make this clearer?

2023-06-27 14:04 UTC, jhollway commented on vignettes/user.Rmd
>  ```
Could add quite a bit of this to the README? What's the advantage of having it in a vignette?

2023-06-27 14:04 UTC, jhollway commented on vignettes/user.Rmd
Why don't we just make `plot()` methods for the (S3 objects) returned by the `compare_*()` functions?

2023-06-28 16:15 UTC, henriquesposito commented on vignettes/user.Rmd
>  ```
I agree, the README is a better place for this for being more visible! I added some of these to the README, I wonder if we should delete the vignette now?

2023-06-28 16:18 UTC, henriquesposito commented on pkgdown/_pkgdown.yml
> +  - title: "Calling 'many* packages' and inspecting data"
Good catch! This has been updated for consistency and clarity

2023-06-28 16:33 UTC, henriquesposito commented on R/call.R
> +                          variable = NULL, actor = NULL) {
Perhaps it could be, I am not sure. Another option would be to move it to `{manypkgs}` if that makes more sense. 

I wonder as well if `plot_releases()` should perhaps become `call_releases()`?

2023-06-28 16:36 UTC, henriquesposito commented on DESCRIPTION
> +    ggVennDiagram
If we decide to move ahead with `manygraph()` then yes, that could be a nice option. Another alternative is moving some of the specific plotting functions for agreements to either `manynet()` or `manypkgs()` for now.

2023-06-29 07:18 UTC, henriquesposito commented on vignettes/user.Rmd
>  ```
I agree, perhaps either we have a more detailed vignette or we focus on the README and delete the vignette.

2023-06-29 08:44 UTC, jaeltan requested changes
Just some minor labelling issues, thanks @henriquesposito

2023-06-29 08:44 UTC, jaeltan commented on R/call.R
> +#' call_treaties(membs, treaty_type = "bilaterals",
extra 's' in `treaty_type = "bilaterals"`?

2023-06-29 08:44 UTC, jaeltan commented on R/call.R
> +#' call_treaties(membs, variable = c("Title", "Begin"), actor = "StateID")
I think the 's' in stateID is not capitalised

2023-06-29 08:44 UTC, jaeltan commented on R/plot.R
> +#' "StateID", by default.
should be lower 's' in stateID

2023-06-29 08:44 UTC, jaeltan commented on R/plot.R
> +#' #Beg > "2000-01-01" & Beg < "2000-12-12")
Begin instead of Beg

2023-06-29 08:44 UTC, jaeltan commented on R/plot.R
> +#' #Beg > "2000-01-01" & Beg < "2000-01-31")
Begin instead of Beg

2023-06-29 08:44 UTC, jaeltan commented on R/plot.R
> +#' #Beg < "2001-12-31")
Begin instead of Beg

2023-06-29 08:44 UTC, jaeltan commented on R/plot.R
> +#' #Beg > "2000-01-01" & Beg < "2000-12-12")
Begin instead of Beg

2023-06-29 08:44 UTC, jaeltan commented on R/plot.R
> +plot_map <- function(dataset, actor = "StateID", treaty_type = NULL,
stateID instead of StateID

2023-06-29 08:44 UTC, jaeltan commented on tests/testthat/test_compare.R
> +  db1 <- compare_categories(database = emperors, key = "ID", variable = "Beg")
Do we need to change 'Beg' in the emperors database to 'Begin' too?

2023-06-29 09:29 UTC, henriquesposito commented on tests/testthat/test_compare.R
> +  db1 <- compare_categories(database = emperors, key = "ID", variable = "Beg")
Good catch, will do so!

2023-07-04 08:06 UTC, jaeltan reviewed
Thanks @henriquesposito , I just have some clarifications to make about `compare_ranges()` before I add the cheatsheet

2023-07-04 10:25 UTC, henriquesposito commented on R/compare.R
> +#' @details `compare_ranges()` compares the number of observations, variables,
Yeah, ideally they should be but since the columns (i.e. "min") display several values some of which might not be dates, they are all converted to "character". I am not sure how to display this information differently for now, however.

2023-07-04 12:57 UTC, jaeltan approved these changes

2023-07-04 13:53 UTC, merged