Develop
globalgov/manydata pull request #66
Opened 2020-11-23 09:12 UTC by henriquesposito

# Description

This main changes covered by this pull request refer to the fixing the tests for qDatr package setup and related functions. As well, as creating a function for gathering and installing other packages part of the ecosystem and creating a hierarchically vague date class. These are patch changes.

Fixes #61 
Fixes #65 
Closes #50 
Closes #62 
Closes #55 
Closes #64 

# Checklist:

- [ ] I have commented my code in-line, particularly in hard-to-understand areas
- [ ] My code follows the style guidelines of this project
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have documented any functions or data in the corresponding .R scripts so that roxygen can create documentation
- [ ] The package builds on my OS without issues
- [ ] My changes generate no new warnings
- [ ] PR checks all pass for latest commit
- [ ] I have bumped the version by the appropriate increment in the DESCRIPTION file (major, minor, patch)
- [ ] I have updated NEWS.md
- [ ] I have given this pull request an informative title and description

2020-11-23 09:53 UTC, jhollway requested changes

2020-11-23 09:53 UTC, jhollway commented on tests/testthat/test_ambigdate.R
> +})
Either fix ambig_date so that it converts (extreme) future dates to a consistent 9999-12-31 or skip this test for now

2020-11-23 09:53 UTC, jhollway commented on tests/testthat/test_ambigdate.R
> +  expect_match(as.character(min(ambig_date("-1712")[[1]])), "-1712-01-01")
Either fix ambig_date() so that it converts historical dates to expected dates class or skip these tests for now

2020-11-23 09:53 UTC, jhollway commented on inst/templates/qPackage-NEWS.md
> +  * Added `DESCRIPTION` file
Add more lines outlining the actions taken to set up the package

2020-11-23 09:53 UTC, jhollway commented on R/package.R
> +#' If one or more package names are provided, these will be installed from
Expand on the documentation for this function

2020-11-23 09:53 UTC, jhollway commented on R/package.R
> +#' @importFrom stringr str_detect
Add importFrom for as_tibble and fromJSON

2020-11-23 09:53 UTC, jhollway commented on R/ambigdate.R
> +#' @return Nested vector of POSIXct dates that includes
Add much more documentation

2020-11-23 09:53 UTC, jhollway commented on R/ambigdate.R
> +
Reconsider function name

2020-11-23 09:53 UTC, jhollway commented on R/data.R
> +#' @param database Intended (short)name of the dataset
Add more advice/documentation on what a dataset/database or data cube is in our terminology

2020-11-23 09:53 UTC, jhollway commented on R/data.R
> +  usethis::ui_done("Made sure data folder hierarchy exists.")
Need to declare these import dependencies?

2020-11-23 09:53 UTC, jhollway commented on R/data.R
>    # TODO: Add these packages as suggests or maybe have the function install them if necessary
Add these packages as suggests or maybe have the function install them if necessary, and remove this line

2020-11-23 09:53 UTC, jhollway commented on tests/testthat/test_setup_package.R
> +
Decide if this is going to continue giving us issues with R CMD Check, and if so, comment out/pause/delete

2020-11-23 09:53 UTC, jhollway commented on tests/testthat/test_setup_package.R
> +  expect_true(file.exists(paste0(dir, "/.github/CODE_OF_CONDUCT.md")))
Create NAMESPACE and LICENSE without usethis (project) dependency

2020-11-23 14:33 UTC, henriquesposito commented on R/data.R
> +  usethis::ui_done("Made sure data folder hierarchy exists.")
I do not think so, but I do think it is better to read and understand the function when they are declared. In any case, would you like me to remove them?

2020-11-23 17:25 UTC, henriquesposito commented on R/ambigdate.R
> +#' @return Nested vector of POSIXct dates that includes
I am having trouble documenting this function...

2020-11-23 17:27 UTC, henriquesposito commented on tests/testthat/test_ambigdate.R
> +})
For now the tests were skipped, but I think this is an important issue to come back to rather soon. Should I write this as an issue for the future in the board or should this be fixed before this pull request is merged?

2020-11-23 17:32 UTC, henriquesposito commented on R/ambigdate.R
> +
Perhaps the name should be reconsidered, I am not sure though. Here are a few (not so good) suggestions: datecube(), datev(), ambidate(), vagdate(), vdate() and, finally, qdate()...

2020-11-23 17:34 UTC, henriquesposito commented on tests/testthat/test_setup_package.R
> +  expect_true(file.exists(paste0(dir, "/.github/CODE_OF_CONDUCT.md")))
Would you like that setup_package() creates NAMESPACE and LICENSE without using usethis? And, if so, why? I am just making sure I understand the issue here.

2020-11-23 19:05 UTC, jhollway commented on R/ambigdate.R
> +#' @return Nested vector of POSIXct dates that includes
Take a look at the (\dontrun) example above it, as well as the tests, and think about what this function does compared to other functions: it seeks to convert ambiguous and ranged dates into a range of dates, and (soon) extend the date parsing of other packages to more historical and future dates.

2020-11-23 19:05 UTC, jhollway commented on tests/testthat/test_ambigdate.R
> +})
Yes, please add it as an issue so that we can merge soon.

2020-11-23 19:07 UTC, jhollway commented on R/data.R
> +  usethis::ui_done("Made sure data folder hierarchy exists.")
No, not remove: but if we keep them do we need to declare them in the documentation, e.g. `@importFrom usethis ui_done`?

2020-11-23 19:08 UTC, jhollway commented on tests/testthat/test_setup_package.R
> +  expect_true(file.exists(paste0(dir, "/.github/CODE_OF_CONDUCT.md")))
Only necessary if we're going to use `create_test_package()` to test `setup_package()`

2020-11-23 19:20 UTC, jhollway requested changes
Keep up the good work Henrique!

2020-11-23 19:20 UTC, jhollway commented on R/data.R
> +#' form of afrom a dataset which will be connected to others in the future.
spelling. duplication.

What is "in the future"?

2020-11-23 19:20 UTC, jhollway commented on R/data.R
> +#' @param database Intended (short)name of the database. This refers to a domain-issue which the dataset(s) to be
Where should we define "domain-issue"?

2020-11-23 19:20 UTC, jhollway commented on R/data.R
> +#' corrected and connected in the future belongs to. That is, what is the domain-issue of the several datasets
What is "in the future"?

2020-11-23 19:20 UTC, jhollway commented on R/data.R
> +#' to be connected belong to. By connecting two-dimensional datasets, we can forma a three-dimensional database
spelling: "forma"

2020-11-23 19:20 UTC, jhollway commented on R/data.R
> +#' that resembles a data cube.
Where should we define "data cube"?

2020-11-23 19:20 UTC, jhollway commented on R/data.R
> +                        # type = NULL,
What is `type`?

2020-11-23 19:20 UTC, jhollway commented on R/data.R
> +            path=getwd())
spaces around equals sign

2020-11-23 19:20 UTC, jhollway commented on R/package.R
> +#' @param path A string for a particular path. Defaults to the current working directory.
Path to...?

2020-11-23 19:20 UTC, jhollway commented on R/package.R
> +                          path) {
keep consistent: `path` and then `if(missing(path))...` or `path = getwd()` like elsewhere

2020-11-23 19:22 UTC, jhollway commented
@henriquesposito don't forget to fill in the checklist at the bottom of the PR description as you go. Make sure you remember to bump the version number in DESCRIPTION (did any old functionality break?) and fill in the NEWS.

2020-11-26 09:43 UTC, jhollway requested changes

2020-11-26 09:43 UTC, jhollway commented on R/ambigdate.R
> +  # dates <- stringr::str_replace_all(dates, "01:01:2022 - 12:12:9999", "01:01:9999")
Delete

2020-11-26 11:47 UTC, jhollway requested changes

2020-11-26 11:47 UTC, jhollway commented on NEWS.md
> +* Fixes #61 by adding and updating tests for `setup_package()`, `import_data()` and `export_data()`
Adding or updating?

2020-11-26 11:47 UTC, jhollway commented on NEWS.md
> +* Closes #65 by correcting issues with the path call in export_data() function
Put `export_data()` in code fences

2020-11-26 11:47 UTC, jhollway commented on NEWS.md
> +* Closes #62 by creating a function which vectorizes dates and cleans and standardizes diverse date formats, `standirdise_dates()`
Spelling of function name important

2020-11-26 11:47 UTC, jhollway commented on NEWS.md
> +* Closes #64 by creating the `get_packages()` function which displays other packages, and some information about these packages, in the qDatr ecosystem
And serves as a wrapper for downloading qPackages from GitHub

2020-11-26 11:58 UTC, jhollway requested changes

2020-11-26 11:58 UTC, jhollway commented on NEWS.md
> +* Closes #64 by creating the `get_packages()` function which displays other packages, and some information about these packages, in the qDatr ecosystem. the function serves as a wrapper for downloadi
Capitalisation? 

Were there any other notices on spelling etc from the checks?

2020-11-26 16:05 UTC, jhollway requested changes

2020-11-26 16:05 UTC, jhollway commented on R/data.R
> +#' @param dataset Intended (short) name of the dataset. This refers to the two-diemnsional sheet of data in the
Spelling

2020-11-26 16:22 UTC, jhollway approved these changes

2020-11-26 16:22 UTC, merged